# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period_name', models.CharField(max_length=20)),
                ('starting_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually'), ('Bimonthly', 'Bimonthly')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollperiod', to='payroll_period.payrollperiod')),
            ],
        ),
    ]
