# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NocType',
            fields=[
                ('noc_rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('noc_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NOC Type',
            },
        ),
        migrations.CreateModel(
            name='NocProcess',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Issued', 'Issued'), ('Withdraw', 'Withdraw'), ('Not Issued', 'Not Issued')], default='In process', max_length=20)),
                ('noc_apply_date', models.DateField(auto_now=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='media/NOC')),
                ('noc_middle_body_text', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeeForNoc', to=settings.AUTH_USER_MODEL)),
                ('noc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noc_types', to='noc.noctype')),
            ],
        ),
        migrations.CreateModel(
            name='NocApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approving_authority_designation', models.CharField(max_length=50)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('visible', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Withdraw', 'Withdraw'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('noc_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noc_approvals', to='noc.nocprocess')),
            ],
        ),
    ]
