# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NocType',
            fields=[
                ('noc_rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('noc_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NocProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noc_apply_date', models.DateField()),
                ('noc_middle_body_text', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeeForNoc', to=settings.AUTH_USER_MODEL)),
                ('noc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noc_types', to='noc.noctype')),
            ],
        ),
    ]
