# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_basic_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address_line2', models.CharField(max_length=100)),
                ('latitude2', models.FloatField(blank=True, null=True)),
                ('longitude2', models.FloatField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRatingModel',
            fields=[
                ('rating_model_rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('active', models.BooleanField()),
                ('total_marks', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRatingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], default='Open Merit', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='E_Transfer_Process',
            fields=[
                ('e_transfer_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='In Process', max_length=10)),
                ('e_transfer_apply_date', models.DateField(auto_now=True)),
                ('transfer_category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Wedlock', 'Wedlock'), ('Disability/Medical', 'Disability/Medical'), ('Wedlock-Disability/Medical', 'Wedlock-Disability/Medical')], max_length=50)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='media/E-transfer_attachments')),
                ('new_joining_date', models.DateField(blank=True, null=True)),
                ('e_transfer_approval_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transfer_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OpenPosition', to='employee_basic_information.position')),
            ],
        ),
        migrations.CreateModel(
            name='ConcernOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(blank=True, default=True, null=True)),
                ('max_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('marks_obtain', models.PositiveIntegerField(blank=True, null=True)),
                ('e_transfer_approval_date', models.DateField(blank=True, null=True)),
                ('new_joining_effective_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=10, null=True)),
                ('concern_officer_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('e_transfer_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ConcernOfficerApproval', to='transfer_setup.e_transfer_process')),
            ],
            options={
                'verbose_name': 'ConcernOfficerApproval',
                'verbose_name_plural': 'ConcernOfficerApprovals',
            },
        ),
        migrations.CreateModel(
            name='E_Transfer_Rating_Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('system_generated_marks', models.IntegerField(blank=True, null=True)),
                ('concerned_person_marks', models.IntegerField(blank=True, null=True)),
                ('e_transfer_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.e_transfer_process')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='E_Transfer_Window_Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.BooleanField()),
                ('open_position', models.ManyToManyField(to='employee_basic_information.position')),
            ],
        ),
        migrations.AddField(
            model_name='e_transfer_process',
            name='transfer_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OpenPosition', to='transfer_setup.e_transfer_window_period'),
        ),
        migrations.CreateModel(
            name='HRDirectorETransferApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('max_marks', models.PositiveIntegerField()),
                ('marks_obtain', models.PositiveIntegerField()),
                ('e_transfer_approval_date', models.DateField(blank=True, null=True)),
                ('new_joining_effective_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Marked', max_length=10)),
                ('concern_officer_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('e_transfer_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HRDirectorETransferApproval', to='transfer_setup.e_transfer_process')),
            ],
            options={
                'verbose_name': 'HRDirectorETransferApproval',
                'verbose_name_plural': 'HRDirectorETransferApprovals',
            },
        ),
        migrations.CreateModel(
            name='SameDistrictRestrictionRule',
            fields=[
                ('rule_rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('restriction_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_basic_information.job')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRatingModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranfer_type_category', models.CharField(blank=True, max_length=20)),
                ('max_marks', models.IntegerField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model', to='transfer_setup.transferratingmodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='TenureRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('minimum_tenure_months', models.IntegerField()),
                ('total_tenure_months', models.IntegerField()),
                ('factor', models.FloatField(blank=True)),
                ('total_month_served', models.IntegerField(blank=True)),
                ('formula_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('within_district_per_km_marks', models.FloatField(max_length=50)),
                ('within_district_max_marks', models.IntegerField()),
                ('across_district_per_km_marks', models.FloatField(max_length=50)),
                ('from_km', models.IntegerField()),
                ('across_district_max_marks', models.IntegerField()),
                ('allow_district_fixed_marks', models.IntegerField()),
                ('formula_type', models.ForeignKey(limit_choices_to={'name': 'distance'}, on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('formula_type', models.ForeignKey(limit_choices_to={'name': 'disability'}, on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='WedlockRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('within_district_fixed_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('across_district_fixed_marks', models.IntegerField()),
                ('formula_type', models.ForeignKey(limit_choices_to={'name': 'wedlock'}, on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.transferratingtype')),
            ],
        ),
    ]
