# Generated by Django 3.2.23 on 2024-01-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_basic_information', '0014_wing_adg'),
        ('transfer_setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_transfer_process',
            name='disability_attachments',
        ),
        migrations.RemoveField(
            model_name='e_transfer_process',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='e_transfer_process',
            name='transfer_center',
        ),
        migrations.RemoveField(
            model_name='e_transfer_process',
            name='transfer_district',
        ),
        migrations.RemoveField(
            model_name='e_transfer_process',
            name='transfer_division',
        ),
        migrations.RemoveField(
            model_name='e_transfer_process',
            name='transfer_tehsil',
        ),
        migrations.RemoveField(
            model_name='e_transfer_process',
            name='wedlock_attachments',
        ),
        migrations.AddField(
            model_name='e_transfer_process',
            name='attachments',
            field=models.FileField(default=1, upload_to='media/E-transfer_attachments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='e_transfer_process',
            name='e_transfer_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='e_transfer_rating_matrix',
            name='e_transfer_process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.e_transfer_process'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='e_transfer_process',
            name='e_transfer_apply_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='e_transfer_process',
            name='new_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='e_transfer_process',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='In Process', max_length=10),
        ),
        migrations.AlterField(
            model_name='e_transfer_process',
            name='transfer_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OpenPosition', to='transfer_setup.e_transfer_window_period'),
        ),
        migrations.RemoveField(
            model_name='e_transfer_window_period',
            name='open_position',
        ),
        migrations.AddField(
            model_name='e_transfer_window_period',
            name='open_position',
            field=models.ManyToManyField(limit_choices_to={'open_position': True}, to='employee_basic_information.Position'),
        ),
        migrations.CreateModel(
            name='HRDirectorETransferApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('max_marks', models.PositiveIntegerField()),
                ('marks_obtain', models.PositiveIntegerField()),
                ('e_transfer_approval_date', models.DateField(blank=True, null=True)),
                ('new_joining_effective_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Marked', max_length=10)),
                ('concern_officer_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('e_transfer_process', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.e_transfer_process')),
            ],
            options={
                'verbose_name': 'HRDirectorETransferApproval',
                'verbose_name_plural': 'HRDirectorETransferApprovals',
            },
        ),
        migrations.CreateModel(
            name='ConcernOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('max_marks', models.PositiveIntegerField()),
                ('marks_obtain', models.PositiveIntegerField()),
                ('e_transfer_approval_date', models.DateField(blank=True, null=True)),
                ('new_joining_effective_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=10)),
                ('concern_officer_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('e_transfer_process', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transfer_setup.e_transfer_process')),
            ],
            options={
                'verbose_name': 'ConcernOfficerApproval',
                'verbose_name_plural': 'ConcernOfficerApprovals',
            },
        ),
    ]
