# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
import employee_master_data.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('c_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Level_of_Education',
            fields=[
                ('level_of_education_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_of_education', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Level_of_Skill',
            fields=[
                ('level_of_skill_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_of_skill', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContactInformation',
            fields=[
                ('e_c_i_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Home', 'Home'), ('Job', 'Job'), ('Other', 'Other')], max_length=50)),
                ('type', models.CharField(choices=[('Phone', 'Phone'), ('Email-Address', 'Email-Address'), ('Fax', 'Fax'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Telex', 'Telex'), ('URL', 'URL')], max_length=50)),
                ('contact_no_address', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='EmployeeReferance',
            fields=[
                ('emp_ref_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('referance_name', models.CharField(max_length=50)),
                ('relation', models.CharField(choices=[('supervisor', 'Former or Current Supervisor'), ('employer', 'Former or Current Employer'), ('coworker', 'Former or Current Co-worker'), ('professor', 'Former or Current Professor')], max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('years_known', models.IntegerField()),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PK')),
                ('company_address', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reference',
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('e_h_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=30)),
                ('position_held', models.CharField(max_length=30)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField()),
                ('leaving_reason', models.CharField(max_length=50)),
                ('organization_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PK')),
                ('organization_address', models.CharField(max_length=50)),
                ('government_job', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.district')),
            ],
            options={
                'verbose_name': 'History',
            },
        ),
        migrations.CreateModel(
            name='FamilyInformation',
            fields=[
                ('full_name', models.CharField(max_length=45)),
                ('fimaly_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('birth_Date', models.DateField()),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('other', 'Other')], default='other', max_length=20)),
                ('is_dependent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Information',
            },
        ),
        migrations.CreateModel(
            name='DependentEmploymentHistory',
            fields=[
                ('d_e_h_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=30)),
                ('position_held', models.CharField(max_length=30)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('leaving_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PK')),
                ('organization_address', models.CharField(max_length=50)),
                ('government_job', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.district')),
                ('spouse_dependent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.familyinformation')),
            ],
            options={
                'verbose_name': 'Dependent History',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('education', models.CharField(max_length=30)),
                ('major_subject', models.CharField(max_length=15)),
                ('institution_name', models.CharField(max_length=30)),
                ('education_start_date', models.DateField()),
                ('education_end_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=employee_master_data.models.Education.upload_path)),
                ('grade', models.CharField(max_length=5)),
                ('scale', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.countries')),
                ('level_of_education', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.level_of_education')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Document',
            fields=[
                ('personal_document_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=25)),
                ('document_name', models.CharField(max_length=25)),
                ('issuance_authority', models.CharField(max_length=25)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('renewal_require', models.BooleanField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField()),
                ('attachment', models.FileField(upload_to='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Document',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('p_i_id', models.AutoField(primary_key=True, serialize=False)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10)),
                ('no_of_dependents', models.IntegerField()),
                ('martial_status_date', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('other', 'Other')], default='other', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], default='other', max_length=20)),
                ('birth_date', models.DateField()),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('deceased_date', models.DateField(blank=True, null=True)),
                ('native_language', models.CharField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('urdu', 'Urdu'), ('other', 'Other')], default='other', max_length=20, null=True)),
                ('pastport_number', models.CharField(blank=True, max_length=40, null=True)),
                ('eobi_number', models.CharField(blank=True, max_length=16, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('disability_note', models.CharField(blank=True, max_length=100)),
                ('date_of_superannutation', models.DateField(blank=True, null=True)),
                ('birth_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.cities')),
                ('domicel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domicel', to='employee_master_data.cities')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.countries')),
            ],
            options={
                'verbose_name': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=50)),
                ('skill_date', models.DateField()),
                ('years_of_experience', models.FloatField(max_length=4)),
                ('verified', models.BooleanField()),
                ('verified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('level_of_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.level_of_skill')),
            ],
            options={
                'verbose_name': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehsil_name', models.CharField(max_length=60)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.district')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('e_a_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('Home', 'Home'), ('Job', 'Job'), ('Other', 'Other')], max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.cities')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.district')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_master_data.tehsil')),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_topic', models.CharField(max_length=200)),
                ('training_nature', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('score_required_to_pass', models.CharField(max_length=200)),
                ('obtained_score', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
