# Generated by Django 4.2.5 on 2023-12-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeaddress',
            options={'verbose_name': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='employeecontactinformation',
            options={'verbose_name': 'Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='employeereferance',
            options={'verbose_name': 'Referance'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'Employeement History'},
        ),
        migrations.AlterModelOptions(
            name='familyinformation',
            options={'verbose_name': 'Family Information'},
        ),
        migrations.AlterModelOptions(
            name='personal_document',
            options={'verbose_name': 'Personal Document'},
        ),
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name': 'Personal Information'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skills'},
        ),
    ]
