# Generated by Django 4.2.5 on 2023-12-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master_data', '0002_alter_employeeaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependentemploymenthistory',
            options={'verbose_name': 'Dependent History'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'History'},
        ),
    ]
