# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AARprescribedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_office', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AARProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aar_allpy_Date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Completed', 'Completed')], default='In process', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.ImageField(blank=True, null=True, upload_to='media/aar_process')),
                ('honest', models.BooleanField(blank=True, null=True)),
                ('reported_as_corrupt', models.BooleanField(blank=True, null=True)),
                ('service_level', models.CharField(blank=True, choices=[('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average')], max_length=50, null=True)),
                ('pen_picture_countersigning_officer', models.TextField(blank=True, null=True)),
                ('useful', models.BooleanField(blank=True, null=True)),
                ('refer_to_compentent_authority', models.BooleanField(blank=True, default=False, null=True)),
                ('compentent_authority_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AARProcessHO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aar_allpy_Date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Completed', 'Completed')], default='In process', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.ImageField(blank=True, null=True, upload_to='media/aar_ho_process')),
                ('job_description', models.TextField()),
                ('brief_achievements', models.TextField()),
                ('officer_performance', models.TextField(blank=True, null=True)),
                ('quality_of_work', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('output_of_work', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('integrity_general', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('integrity_intellectual', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('pen_picture_reporting_officer', models.TextField(blank=True, null=True)),
                ('area_and_level_of_expertise', models.TextField(blank=True, null=True)),
                ('training_and_development_need', models.BooleanField(blank=True, default=False, null=True)),
                ('overall_grading', models.CharField(blank=True, choices=[('very good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('below average', 'Below Average')], max_length=15, null=True)),
                ('fitness_for_retention', models.TextField(blank=True, null=True)),
                ('frequency_of_work', models.CharField(blank=True, choices=[('very frequently', 'Very Frequently'), ('frequently', 'Frequently'), ('rarely', 'Rarely'), ('never', 'Never')], max_length=20, null=True)),
                ('know_the_officer', models.TextField(blank=True, null=True)),
                ('recommendation_for_retention', models.TextField(blank=True, null=True)),
                ('quality_of_assessment', models.CharField(blank=True, choices=[('exaggerated', 'Exaggerated'), ('fair', 'Fair'), ('biased', 'Biased')], max_length=50, null=True)),
                ('refer_to_compentent_authority', models.BooleanField(blank=True, default=False, null=True)),
                ('compentent_authority_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reporting_officer', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingModelAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RatingTypeLikertScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile_range', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RatingTypePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('max_points', models.IntegerField()),
                ('type', models.CharField(choices=[('system generated', 'system generated'), ('reporting officer', 'reporting officer'), ('counter signing officer', 'counter signing officer')], max_length=50)),
                ('api', models.BooleanField(blank=True, default=False, null=True)),
                ('api_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingTypePointsAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('max_points', models.IntegerField()),
                ('point_earned', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
