# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR_Setups', '0001_initial'),
        ('annual_assessment_setup', '0001_initial'),
        ('employee_basic_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aarcompetentauthorityapproval',
            name='competent_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AARCompetentAuthorityApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='counter_assigning_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AARCounterAssigningOfficerApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aarhocounterassigningofficerapproval',
            name='counter_assigning_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AARCounterAssigningOfficerApprovals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aarhoreportingofficerapproval',
            name='reporting_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AARHOReportingOfficerApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aarprescribedform',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_basic_information.job', unique=True),
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR_Setups.hrcelanderyear'),
        ),
        migrations.AddField(
            model_name='aarhoreportingofficerapproval',
            name='aar_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess'),
        ),
        migrations.AddField(
            model_name='aarhocounterassigningofficerapproval',
            name='aar_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess'),
        ),
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='aar_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess'),
        ),
        migrations.AddField(
            model_name='aarcompetentauthorityapproval',
            name='aar_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess'),
        ),
        migrations.AddField(
            model_name='aarreportingofficerapproval',
            name='aar_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aarreportingofficerapproval_set', to='annual_assessment_setup.aarprocess'),
        ),
        migrations.AddField(
            model_name='aarreportingofficerapproval',
            name='reporting_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AARReportingOfficerApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_basic_information.job'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR_Setups.hrcelanderyear'),
        ),
        migrations.AddField(
            model_name='ratingtypelikertscale',
            name='rating_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'Likert Scale'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingmodel'),
        ),
        migrations.AddField(
            model_name='aarreportingofficerapproval',
            name='over_All_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingtypelikertscale'),
        ),
        migrations.AddField(
            model_name='aarhocounterassigningofficerapproval',
            name='over_All_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingtypelikertscale'),
        ),
        migrations.AddField(
            model_name='ratingtypepoints',
            name='rating_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'Points'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingmodel'),
        ),
        migrations.AddField(
            model_name='ratingtypepointsassignment',
            name='aar_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RatingTypePointsAssignment', to='annual_assessment_setup.aarprocess'),
        ),
        migrations.AddField(
            model_name='ratingtypepointsassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ratingmodel',
            unique_together={('year', 'type', 'job', 'active')},
        ),
    ]
