# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_basic_information', '0001_initial'),
        ('annual_assessment_setup', '0001_initial'),
        ('HR_Setups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingtypepointsassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingtypepoints',
            name='rating_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__name': 'Points'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingmodel'),
        ),
        migrations.AddField(
            model_name='ratingtypelikertscale',
            name='rating_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__name': 'Likert Scale'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingmodel'),
        ),
        migrations.AddField(
            model_name='ratingmodelassignment',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_basic_information.job'),
        ),
        migrations.AddField(
            model_name='ratingmodelassignment',
            name='rating_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annual_assessment_setup.ratingmodel'),
        ),
        migrations.AddField(
            model_name='ratingmodelassignment',
            name='year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='HR_Setups.hrcelanderyear'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annual_assessment_setup.ratingmodeltype'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR_Setups.hrcelanderyear'),
        ),
        migrations.AddField(
            model_name='aarprocessho',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aarprocessho',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR_Setups.hrcelanderyear'),
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='over_All_grading',
            field=models.ForeignKey(blank=True, limit_choices_to={'rating_model__reporting_officer': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingtypelikertscale'),
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR_Setups.hrcelanderyear'),
        ),
        migrations.AddField(
            model_name='aarprescribedform',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_basic_information.job'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingmodel',
            unique_together={('year', 'type', 'reporting_officer')},
        ),
    ]
