# Generated by Django 5.0 on 2023-12-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aarprocess',
            old_name='aar_allpy_Date',
            new_name='aar_apply_Date',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='compentent_authority_remarks',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='honest',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='over_All_grading',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='pen_picture_countersigning_officer',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='refer_to_compentent_authority',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='reported_as_corrupt',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='service_level',
        ),
        migrations.RemoveField(
            model_name='aarprocess',
            name='useful',
        ),
        migrations.AddField(
            model_name='ratingtypepointsassignment',
            name='aar_request_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annual_assessment_setup.aarprocess'),
            preserve_default=False,
        ),
    ]
