# Generated by Django 5.0 on 2023-12-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0003_rename_aar_allpy_date_aarprocess_aar_apply_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AARCompetentAuthorityApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('compentent_authority_remarks', models.TextField(blank=True, null=True)),
                ('aar_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess')),
                ('competent_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AARCompetentAuthorityApproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AARCounterAssigningOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honest', models.BooleanField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('reported_as_corrupt', models.BooleanField(blank=True, null=True)),
                ('service_level', models.CharField(blank=True, choices=[('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average')], max_length=50, null=True)),
                ('pen_picture_countersigning_officer', models.TextField(blank=True, null=True)),
                ('useful', models.BooleanField(blank=True, null=True)),
                ('aar_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess')),
                ('counter_assigning_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AARCounterAssigningOfficerApproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AARReportingOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.ImageField(blank=True, null=True, upload_to='media/aar_process')),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Approved', 'Approved')], default='In Process', max_length=20)),
                ('aar_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess')),
                ('over_All_grading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.ratingtypelikertscale')),
                ('reporting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AARReportingOfficerApproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
