# Generated by Django 5.0 on 2023-12-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0004_aarcompetentauthorityapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Refer to Competent Authority', 'Refer to Competent Authority'), ('Approved', 'Approved')], default='In Process', max_length=36),
        ),
    ]
