# Generated by Django 5.0 on 2023-12-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0005_aarcounterassigningofficerapproval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aarcompetentauthorityapproval',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Approved', 'Approved')], default='In Process', max_length=36),
        ),
    ]
