# Generated by Django 5.0 on 2023-12-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0007_alter_ratingmodel_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingModelAssignment',
        ),
    ]
