# Generated by Django 5.0 on 2023-12-29 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0008_delete_ratingmodelassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='aarcounterassigningofficerapproval',
            old_name='compentent_authority_remarks',
            new_name='pen_picture_countersigning_officer',
        ),
        migrations.RemoveField(
            model_name='aarcounterassigningofficerapproval',
            name='frequency_of_work',
        ),
        migrations.RemoveField(
            model_name='aarcounterassigningofficerapproval',
            name='know_the_officer',
        ),
        migrations.RemoveField(
            model_name='aarcounterassigningofficerapproval',
            name='quality_of_assessment',
        ),
        migrations.RemoveField(
            model_name='aarcounterassigningofficerapproval',
            name='recommendation_for_retention',
        ),
        migrations.RemoveField(
            model_name='aarcounterassigningofficerapproval',
            name='refer_to_compentent_authority',
        ),
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='honest',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='reported_as_corrupt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='service_level',
            field=models.CharField(blank=True, choices=[('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='useful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aarcounterassigningofficerapproval',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AARHOCounterAssigningOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_of_work', models.CharField(blank=True, choices=[('very frequently', 'Very Frequently'), ('frequently', 'Frequently'), ('rarely', 'Rarely'), ('never', 'Never')], max_length=20, null=True)),
                ('know_the_officer', models.TextField(blank=True, null=True)),
                ('recommendation_for_retention', models.TextField(blank=True, null=True)),
                ('quality_of_assessment', models.CharField(blank=True, choices=[('exaggerated', 'Exaggerated'), ('fair', 'Fair'), ('biased', 'Biased')], max_length=50, null=True)),
                ('refer_to_compentent_authority', models.BooleanField(blank=True, default=False, null=True)),
                ('compentent_authority_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Refer to Competent Authority', 'Refer to Competent Authority'), ('Approved', 'Approved')], default='In Process', max_length=36)),
                ('aar_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annual_assessment_setup.aarprocess')),
                ('counter_assigning_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AARCounterAssigningOfficerApprovals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
