# Generated by Django 5.0 on 2023-12-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0009_rename_compentent_authority_remarks_aarcounterassigningofficerapproval_pen_picture_countersigning_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aarhocounterassigningofficerapproval',
            name='compentent_authority_remarks',
        ),
        migrations.RemoveField(
            model_name='aarhocounterassigningofficerapproval',
            name='refer_to_compentent_authority',
        ),
    ]
