# Generated by Django 5.0 on 2023-12-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0010_remove_aarhocounterassigningofficerapproval_compentent_authority_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aarhocounterassigningofficerapproval',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
