# Generated by Django 5.0 on 2023-12-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0011_aarhocounterassigningofficerapproval_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aarreportingofficerapproval',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='aarreportingofficerapproval',
            name='notes',
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='media/aar_process'),
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
