# Generated by Django 5.0 on 2023-12-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0012_remove_aarreportingofficerapproval_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aarprocessho',
            name='brief_achievements',
        ),
        migrations.RemoveField(
            model_name='aarprocessho',
            name='job_description',
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='brief_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aarprocess',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
