# Generated by Django 3.2.23 on 2024-01-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_assessment_setup', '0013_remove_aarprocessho_brief_achievements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AARProcessHO',
        ),
    ]
