# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_basic_information', '0001_initial'),
        ('HR_Setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRatingModel',
            fields=[
                ('rating_model_rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('total_marks', models.IntegerField(default=100)),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='simpleTransferYear', to='HR_Setups.hrcelanderyear')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRatingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], default='Open Merit', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WedlockRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('within_district_fixed_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('across_district_fixed_marks', models.IntegerField()),
                ('formula_type', models.ForeignKey(limit_choices_to={'name': 'wedlock'}, on_delete=django.db.models.deletion.PROTECT, related_name='forType', to='simple_transfer_Setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRatingModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranfer_typcategory', models.CharField(blank=True, max_length=20)),
                ('max_marks', models.IntegerField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simpleTransfer', to='simple_transfer_Setup.transferratingmodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typeSimpleTransfer', to='simple_transfer_Setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Rating_Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('system_generated_marks', models.IntegerField()),
                ('concerned_person_marks', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empPosition', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Process',
            fields=[
                ('transfer_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], max_length=10)),
                ('transfer_apply_date', models.DateField()),
                ('transfer_division', models.CharField(max_length=20)),
                ('transfer_district', models.CharField(max_length=20)),
                ('transfer_tehsil', models.CharField(max_length=20)),
                ('transfer_center', models.CharField(max_length=20)),
                ('transfer_category', models.CharField(choices=[('Administrative', 'Administrative'), ('Inquiry', 'Inquiry'), ('Wedlock', 'Wedlock'), ('Disability/Medical', 'Disability/Medical'), ('Wedlock-Disability/Medical', 'Wedlock-Disability/Medical')], max_length=50)),
                ('remarks', models.CharField(max_length=100)),
                ('wedlock_attachments', models.FileField(upload_to='media/transfer_attachments')),
                ('disability_attachments', models.FileField(upload_to='media/transfer_attachments')),
                ('new_joining_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emp', to=settings.AUTH_USER_MODEL)),
                ('transfer_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OpenPositionSimpleTransfer', to='employee_basic_information.position')),
            ],
        ),
        migrations.CreateModel(
            name='TenureRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('minimum_tenurmonths', models.IntegerField()),
                ('total_tenurmonths', models.IntegerField()),
                ('factor', models.FloatField(blank=True)),
                ('formula_type', models.ForeignKey(limit_choices_to={'name': 'tenure'}, on_delete=django.db.models.deletion.PROTECT, related_name='formulaType', to='simple_transfer_Setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='SameDistrictRestrictionRule',
            fields=[
                ('rulrec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('restriction_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SameDistrictRestrictionRuleJob', to='employee_basic_information.job')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('within_district_per_km_marks', models.FloatField(max_length=50)),
                ('within_district_max_marks', models.IntegerField()),
                ('across_district_per_km_marks', models.FloatField(max_length=50)),
                ('from_km', models.IntegerField()),
                ('across_district_max_marks', models.IntegerField()),
                ('allow_district_fixed_marks', models.IntegerField()),
                ('formula_type', models.ForeignKey(limit_choices_to={'name': 'distance'}, on_delete=django.db.models.deletion.PROTECT, related_name='formulaTypeSimpleTransfer', to='simple_transfer_Setup.transferratingtype')),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityRatingFarmula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Open Merit', 'Open Merit'), ('Hardship', 'Hardship')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('formula_type', models.ForeignKey(limit_choices_to={'name': 'disability'}, on_delete=django.db.models.deletion.PROTECT, related_name='disabilityFormulaType', to='simple_transfer_Setup.transferratingtype')),
            ],
        ),
    ]
