# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_basic_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_Process',
            fields=[
                ('transfer_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='In Process', max_length=10)),
                ('transfer_apply_date', models.DateField(auto_now=True)),
                ('transfer_approval_date', models.DateField(blank=True, null=True)),
                ('transfer_category', models.CharField(choices=[('Administrative', 'Administrative'), ('Inquiry', 'Inquiry'), ('Wedlock', 'Wedlock'), ('Disability/Medical', 'Disability/Medical'), ('Wedlock-Disability/Medical', 'Wedlock-Disability/Medical')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='media/administrative_transfer_attachments')),
                ('new_joining_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emp', to=settings.AUTH_USER_MODEL)),
                ('transfer_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OpenPositionSimpleTransfer', to='employee_basic_information.position')),
            ],
        ),
        migrations.CreateModel(
            name='TransferApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('Joining_effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TransferApprovals', to=settings.AUTH_USER_MODEL)),
                ('transfer_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_process', to='simple_transfer_Setup.transfer_process')),
            ],
        ),
    ]
