# Generated by Django 3.2.23 on 2024-01-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_transfer_Setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('Joining_effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TransferApprovals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='distanceratingfarmula',
            name='formula_type',
        ),
        migrations.RemoveField(
            model_name='samedistrictrestrictionrule',
            name='restriction_job',
        ),
        migrations.RemoveField(
            model_name='tenureratingfarmula',
            name='formula_type',
        ),
        migrations.RemoveField(
            model_name='transfer_rating_matrix',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='transferratingmodel',
            name='year',
        ),
        migrations.RemoveField(
            model_name='transferratingmodeltype',
            name='model',
        ),
        migrations.RemoveField(
            model_name='transferratingmodeltype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='wedlockratingfarmula',
            name='formula_type',
        ),
        migrations.RemoveField(
            model_name='transfer_process',
            name='disability_attachments',
        ),
        migrations.RemoveField(
            model_name='transfer_process',
            name='transfer_center',
        ),
        migrations.RemoveField(
            model_name='transfer_process',
            name='transfer_district',
        ),
        migrations.RemoveField(
            model_name='transfer_process',
            name='transfer_division',
        ),
        migrations.RemoveField(
            model_name='transfer_process',
            name='transfer_tehsil',
        ),
        migrations.RemoveField(
            model_name='transfer_process',
            name='wedlock_attachments',
        ),
        migrations.AddField(
            model_name='transfer_process',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='media/administrative_transfer_attachments'),
        ),
        migrations.AddField(
            model_name='transfer_process',
            name='transfer_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_process',
            name='new_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_process',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_process',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='In Process', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfer_process',
            name='transfer_apply_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='DisabilityRatingFarmula',
        ),
        migrations.DeleteModel(
            name='DistanceRatingFarmula',
        ),
        migrations.DeleteModel(
            name='SameDistrictRestrictionRule',
        ),
        migrations.DeleteModel(
            name='TenureRatingFarmula',
        ),
        migrations.DeleteModel(
            name='Transfer_Rating_Matrix',
        ),
        migrations.DeleteModel(
            name='TransferRatingModel',
        ),
        migrations.DeleteModel(
            name='TransferRatingModelType',
        ),
        migrations.DeleteModel(
            name='TransferRatingType',
        ),
        migrations.DeleteModel(
            name='WedlockRatingFarmula',
        ),
        migrations.AddField(
            model_name='transferapprovals',
            name='transfer_process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='simple_transfer_Setup.transfer_process'),
        ),
    ]
