# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevtionDocument',
            fields=[
                ('elevtion_to_l2_doc_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_date', models.DateField()),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Close', 'Close')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PendingElevation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField()),
                ('months_in_current_level', models.IntegerField()),
                ('current_level_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Process', 'In Process'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ElevtionToEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_to_level', models.IntegerField()),
                ('elevation_approval_date', models.DateField(blank=True, null=True)),
                ('elevation_effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], max_length=20)),
                ('approved_by', models.CharField(blank=True, choices=[('DG', 'DG'), ('Hr Director', 'Hr Director')], max_length=20, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toL2', to='elevation.elevtiondocument')),
            ],
        ),
    ]
