# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevtionToL2',
            fields=[
                ('elevtion_to_l2_doc_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_date', models.DateField()),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Close', 'Close')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElevtionToL2Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation_approval_date', models.DateField(blank=True, null=True)),
                ('elevation_effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElevtionToL3',
            fields=[
                ('elevtion_to_l3_doc_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_date', models.DateField()),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Close', 'Close')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElevtionToL3Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation_approval_date', models.DateField(blank=True, null=True)),
                ('elevation_effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toL2', to='elevation.elevtiontol3')),
            ],
        ),
    ]
