# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elevation', '0001_initial'),
        ('employee_basic_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elevtiontoemployee',
            name='elevation_job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elevationjoblevelL2', to='employee_basic_information.joblevel'),
        ),
        migrations.AddField(
            model_name='elevtiontoemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toL2Employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingelevation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendingEmployeesForElevation', to=settings.AUTH_USER_MODEL),
        ),
    ]
