# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_basic_information', '0001_initial'),
        ('elevation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevtiontol3employee',
            name='elevation_job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elevationjoblevel', to='employee_basic_information.joblevel'),
        ),
        migrations.AddField(
            model_name='elevtiontol3employee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toL3Employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elevtiontol2employee',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toL2', to='elevation.elevtiontol2'),
        ),
        migrations.AddField(
            model_name='elevtiontol2employee',
            name='elevation_job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elevationjoblevelL2', to='employee_basic_information.joblevel'),
        ),
        migrations.AddField(
            model_name='elevtiontol2employee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toL2Employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
