# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_basic_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approving_authority', models.CharField(choices=[('REPORTING OFFICER', 'REPORTING OFFICER'), ('DIRECTOR CONCERN', 'DIRECTOR CONCERN'), ('ADG ADMIN', 'ADG ADMIN'), ('DG', 'DG')], default='ADG ADMIN', max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('approving_time', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Leave Approval Setup',
            },
        ),
        migrations.CreateModel(
            name='LeaveCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveSmallIntegerField(unique=True)),
                ('max_count', models.PositiveSmallIntegerField(unique=True)),
                ('total_approvals_days', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=50)),
                ('leave_description', models.CharField(max_length=255)),
                ('visible_at_leave_apply_time', models.BooleanField()),
                ('gender_eligibility', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('All', 'All')], max_length=20)),
                ('accrue', models.BooleanField()),
                ('prorate_calculation', models.BooleanField(blank=True, null=True)),
                ('accrue_annual_limit', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('accrue_per_month', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('add_in_first_hr_month', models.IntegerField(blank=True, null=True)),
                ('balance_paid_annually', models.BooleanField(blank=True, null=True)),
                ('earning_code', models.CharField(blank=True, max_length=50, null=True)),
                ('entire_service_validity', models.BooleanField()),
                ('avail_number_of_times', models.IntegerField(blank=True, null=True)),
                ('one_time_avail_limit', models.IntegerField(blank=True, null=True)),
                ('entire_service_limit', models.IntegerField(blank=True, null=True)),
                ('leave_dependency', models.BooleanField()),
                ('salary_deduction_eligibility_rule', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('leave_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_year_id', models.IntegerField(blank=True, null=True)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_count', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Approved', 'Approved'), ('Withdraw', 'Withdraw'), ('Rejected', 'Rejected')], default='In Process', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('report_back_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leave_deduction_bucket_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_apply_deduction_headers', to='leave_setup.leavetype')),
                ('leave_type', models.ForeignKey(limit_choices_to={'visible_at_leave_apply_time': True}, on_delete=django.db.models.deletion.PROTECT, related_name='leave_apply_type_headers', to='leave_setup.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('system_approval', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdraw', 'Withdraw'), ('-', '-')], default='Pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapply')),
                ('leave_approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapprovals')),
            ],
        ),
        migrations.AddField(
            model_name='leaveapprovals',
            name='leave_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_setup.leavecount'),
        ),
        migrations.CreateModel(
            name='LeaveDependableDetail',
            fields=[
                ('l_d_d_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_year_id', models.IntegerField()),
                ('apply_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('attendance_validation', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapply')),
                ('leave_deduction_bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_dependable_deduction_headers', to='leave_setup.leavetype')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_dependable_headers', to='leave_setup.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveNonDependableDetail',
            fields=[
                ('l_n_d_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_year_id', models.IntegerField()),
                ('apply_date', models.DateField()),
                ('leave_from_date', models.DateField()),
                ('leave_to_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('leave_type_allowed', models.IntegerField(blank=True, null=True)),
                ('leave_type_used', models.IntegerField(blank=True, null=True)),
                ('leave_type_remaning', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapply')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_non_dependable_headers', to='leave_setup.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDependableBucket',
            fields=[
                ('l_d_b_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_deduction_bucket_allowed', models.IntegerField(blank=True, default=0, null=True)),
                ('leave_deduction_used', models.IntegerField(blank=True, default=0, null=True)),
                ('leave_type_used', models.IntegerField(blank=True, default=0, null=True)),
                ('leave_deduction_running_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('LeaveDependableDetail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leavedependabledetail')),
                ('leave_deduction_bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_dependable_deduction_headers_bucket', to='leave_setup.leavetype')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_dependable_headers_bucket', to='leave_setup.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='AccrueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('hr_year', models.IntegerField()),
                ('accrued_leaves', models.IntegerField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_apply_type_headers_accrue', to='leave_setup.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='SuperApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_start_date', models.DateField(blank=True, null=True)),
                ('position_end_date', models.DateField(blank=True, null=True)),
                ('ready_for_position_assignment', models.BooleanField(default=False)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdraw', 'Withdraw'), ('-', '-')], default='Pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('additional_position_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_position_assignment', to=settings.AUTH_USER_MODEL)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapply')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('depends_upon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependency_of_leaves', to='leave_setup.leavetype')),
                ('leave_with_adjustable', models.ForeignKey(limit_choices_to={'leave_dependency': True}, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_leaves', to='leave_setup.leavetype')),
            ],
            options={
                'unique_together': {('leave_with_adjustable', 'depends_upon')},
            },
        ),
        migrations.CreateModel(
            name='SalaryDeductible',
            fields=[
                ('s_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.ForeignKey(limit_choices_to={'salary_deduction_eligibility_rule': True}, on_delete=django.db.models.deletion.PROTECT, related_name='salary_deductible_leave_types', to='leave_setup.leavetype')),
                ('ppg_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_basic_information.ppg_level_setup')),
            ],
            options={
                'unique_together': {('leave_type', 'ppg_level')},
            },
        ),
    ]
