# Generated by Django 4.2.5 on 2023-12-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Leave Type Setup'},
        ),
        migrations.AlterModelOptions(
            name='salarydeductible',
            options={'verbose_name': 'Salary Deductible Role'},
        ),
    ]
