# Generated by Django 4.2.5 on 2023-12-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_setup', '0002_alter_leavetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavedependency',
            options={'verbose_name': 'Leave Adjustable Dependency'},
        ),
    ]
