# Generated by Django 5.0 on 2023-12-21 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_setup', '0003_alter_leavedependency_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approving_authority', models.CharField(choices=[('REPORTING OFFICER', 'REPORTING OFFICER'), ('DIRECTO CONCERN', 'DIRECTO CONCERN'), ('ADG ADMIN', 'ADG ADMIN'), ('DG', 'DG')], default='ADG ADMIN', max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('approving_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveSmallIntegerField()),
                ('max_count', models.PositiveSmallIntegerField()),
                ('total_approvals_days', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='leavedependency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salarydeductible',
            options={},
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Approved', 'Approved'), ('Withdraw', 'Withdraw'), ('Rejected', 'Rejected')], default='In Process', max_length=20),
        ),
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('system_approval', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapply')),
                ('leave_approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapprovals')),
            ],
        ),
        migrations.AddField(
            model_name='leaveapprovals',
            name='leave_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leavecount'),
        ),
        migrations.CreateModel(
            name='SuperApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_setup.leaveapply')),
            ],
        ),
    ]
