# Generated by Django 5.0 on 2023-12-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_setup', '0004_leaveapprovals_leavecount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecount',
            name='max_count',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='leavecount',
            name='min_count',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
