# Generated by Django 3.2.23 on 2024-01-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0014_wing_adg'),
        ('leave_setup', '0006_alter_leaveapprovals_approving_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='superapprovals',
            name='position_assignment_for_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_assignment_for_leave', to='employee_basic_information.positionassignment'),
        ),
        migrations.AlterField(
            model_name='superapprovals',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
