# Generated by Django 3.2.23 on 2024-01-18 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_setup', '0007_auto_20240117_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superapprovals',
            name='position_assignment_for_leave',
        ),
        migrations.AddField(
            model_name='superapprovals',
            name='additional_position_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_position_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
