# Generated by Django 3.2.23 on 2024-01-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_setup', '0008_auto_20240118_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superapprovals',
            name='position_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superapprovals',
            name='position_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superapprovals',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
