# Generated by Django 3.2.23 on 2024-01-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_setup', '0009_auto_20240122_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accruetable',
            name='leave_bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_apply_type_headers_accrue', to='leave_setup.leavetype'),
        ),
    ]
