# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryProceedingInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_start_date', models.DateField(blank=True, null=True)),
                ('inquiry_status', models.CharField(choices=[('In process', 'In process'), ('Closed', 'Closed')], default='In process', max_length=20)),
                ('inquiry_reason', models.CharField(choices=[('Intelligence report', 'Intelligence report'), ('Complaint', 'Complaint'), ('Corruption', 'Corruption'), ('Misconduct', 'Misconduct'), ('Inefficiency', 'Inefficiency'), ('Reference from DC/AC', 'Reference from DC/AC'), ('Other', 'Other')], max_length=50)),
                ('remarks_for_other_inquiry_reason', models.TextField(blank=True)),
                ('attachment_of_probe_report', models.FileField(blank=True, upload_to='probe_reports/')),
                ('submission_of_probe_report_date', models.DateField(blank=True, null=True)),
                ('submit_probe_report_to_competent_authority', models.BooleanField(default=False)),
                ('allegation_status', models.CharField(blank=True, choices=[('Proved', 'Proved'), ('Unproved', 'Unproved')], max_length=20)),
                ('personal_hearing_notice', models.BooleanField(default=False)),
                ('attachment_of_personal_hearing_notice', models.FileField(blank=True, upload_to='hearing_notices/')),
                ('issuance_of_personal_hearing_notice_date', models.DateField(blank=True, null=True)),
                ('initiate_regular_inquiry', models.BooleanField(default=False)),
                ('regular_inquiry_start_date', models.DateField(blank=True, null=True)),
                ('hr_alert_date_probe_report', models.DateField(blank=True, null=True)),
                ('attachment_of_inquiry_order', models.FileField(blank=True, upload_to='inquiry_orders/')),
                ('issuance_of_inquiry_order_date', models.DateField(blank=True, null=True)),
                ('attachment_of_inquiry_report', models.FileField(blank=True, upload_to='inquiry_reports/')),
                ('issuance_of_inquiry_report_date', models.DateField(blank=True, null=True)),
                ('hr_alert_date_issuance_of_inquiry', models.DateField(blank=True, null=True)),
                ('attachment_of_final_order', models.FileField(blank=True, upload_to='final_orders/')),
                ('issuance_of_final_order_date', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(max_length=20)),
                ('inquiry_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('nature', models.CharField(choices=[('No Input', 'No Input'), ('Date', 'Date'), ('Amount', 'Amount')], max_length=50)),
                ('inquiryoutcomes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes')),
            ],
        ),
    ]
