# Generated by Django 5.0 on 2024-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DGFinalApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DGFirstApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('probe_allegation_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Unapproved', 'Unapproved')], default='Pending', max_length=20)),
                ('probe_allegation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorHrApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('issuance_of_final_order_date', models.DateField(blank=True, null=True)),
                ('attachment_of_final_order', models.FileField(blank=True, upload_to='final_orders/')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to DG', 'Refer to DG'), ('Closed', 'Closed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryProceedingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_reason', models.CharField(choices=[('Intelligence report', 'Intelligence report'), ('Complaint', 'Complaint'), ('Corruption', 'Corruption'), ('Misconduct', 'Misconduct'), ('Inefficiency', 'Inefficiency'), ('Reference from DC/AC', 'Reference from DC/AC'), ('Other', 'Other')], max_length=50)),
                ('remarks_for_other_inquiry_reason', models.TextField(blank=True, null=True)),
                ('inquiry_start_date', models.DateField(blank=True, null=True)),
                ('inquiry_status', models.CharField(choices=[('In process', 'In process'), ('Closed', 'Closed')], default='In process', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HRUserApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_of_personal_hearing_notice_date', models.DateField(blank=True, null=True)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('attachment_of_personal_hearing_notice', models.FileField(blank=True, upload_to='hearing_notices/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to Director HR', 'Refer to Director HR')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_name', models.CharField(max_length=20)),
                ('inquiry_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('nature', models.CharField(choices=[('No Input', 'No Input'), ('Date', 'Date'), ('Amount', 'Amount')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProbeOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('issuance_of_probe_report_date', models.DateField(blank=True, null=True)),
                ('attachment_of_probe_report', models.FileField(blank=True, upload_to='probe_reports/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to DG', 'Refer to DG')], default='Pending', max_length=20)),
                ('alert_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegularInquiryOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_of_inquiry_order_date', models.DateField(blank=True, null=True)),
                ('attachment_of_inquiry_order', models.FileField(blank=True, upload_to='inquiry_order/')),
                ('alert_date_inquiry_order', models.DateField(blank=True, null=True)),
                ('alert_date_inquiry_report', models.DateField(blank=True, null=True)),
                ('issuance_of_inquiry_report_date', models.DateField(blank=True, null=True)),
                ('attachment_of_inquiry_report', models.FileField(blank=True, upload_to='inquiry_report/')),
                ('status_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to Director HR', 'Refer to Director HR')], default='Pending', max_length=20)),
            ],
        ),
    ]
