# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinary_proceedings_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dgfinalapproval',
            name='approving_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFinalApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dgfirstapproval',
            name='approving_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFirstApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directorhrapproval',
            name='approving_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DirectorHrApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedingrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DisciplinaryProceedingRequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedingrequest',
            name='prob_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DisciplinaryProceedingRequest_prob_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedingrequest',
            name='regular_inquiry_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DisciplinaryProceedingRequest_regular_inquiry_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directorhrapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DirectorHrApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='dgfirstapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFirstApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='dgfinalapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFinalApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='hruserapproval',
            name='approving_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HRUserApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hruserapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HRUserApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='directorhrapproval',
            name='inquiry_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes'),
        ),
        migrations.AddField(
            model_name='dgfinalapproval',
            name='inquiry_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes'),
        ),
        migrations.AddField(
            model_name='inquirytype',
            name='inquiryoutcomes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes'),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedingrequest',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquirytype'),
        ),
        migrations.AddField(
            model_name='directorhrapproval',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquirytype'),
        ),
        migrations.AddField(
            model_name='dgfinalapproval',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquirytype'),
        ),
        migrations.AddField(
            model_name='probeofficerapproval',
            name='approving_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProbeOfficerApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probeofficerapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProbeOfficerApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='regularinquiryofficerapproval',
            name='approving_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RegularInquiryOfficer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularinquiryofficerapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RegularInquiryOfficer', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
    ]
