# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplinary_proceedings_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryproceedinginquiry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emoloyee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedinginquiry',
            name='inquiry_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes'),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedinginquiry',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquirytype'),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedinginquiry',
            name='probe_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probe_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryproceedinginquiry',
            name='regular_inquiry_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_inquiry_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
