# Generated by Django 3.2.23 on 2024-01-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplinary_proceedings_setup', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('issuance_of_final_order_date', models.DateField(blank=True, null=True)),
                ('attachment_of_final_order', models.FileField(blank=True, upload_to='final_orders/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to Hr Director', 'Refer to Hr Director'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGApproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DGFinalApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFinalApproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DGFirstApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_allegation_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Proved', 'Proved'), ('Unproved', 'Unproved')], default='Pending', max_length=20)),
                ('probe_allegation_date', models.DateField(blank=True, null=True)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFirstApproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorHrApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('issuance_of_final_order_date', models.DateField(blank=True, null=True)),
                ('attachment_of_final_order', models.FileField(blank=True, upload_to='final_orders/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to DG', 'Refer to DG'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DirectorHrApproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryProceedingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_reason', models.CharField(choices=[('Intelligence report', 'Intelligence report'), ('Complaint', 'Complaint'), ('Corruption', 'Corruption'), ('Misconduct', 'Misconduct'), ('Inefficiency', 'Inefficiency'), ('Reference from DC/AC', 'Reference from DC/AC'), ('Other', 'Other')], max_length=50)),
                ('remarks_for_other_inquiry_reason', models.TextField(blank=True, null=True)),
                ('inquiry_start_date', models.DateField(blank=True, null=True)),
                ('inquiry_status', models.CharField(choices=[('In process', 'In process'), ('Closed', 'Closed')], default='In process', max_length=20)),
                ('allegation_status', models.CharField(blank=True, choices=[('Proved', 'Proved'), ('Unproved', 'Unproved')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DisciplinaryProceedingRequest', to=settings.AUTH_USER_MODEL)),
                ('prob_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DisciplinaryProceedingRequest_prob_officer', to=settings.AUTH_USER_MODEL)),
                ('regular_inquiry_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DisciplinaryProceedingRequest_regular_inquiry_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HRUserApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_of_personal_hearing_notice_date', models.DateField(blank=True, null=True)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('attachment_of_personal_hearing_notice', models.FileField(blank=True, upload_to='hearing_notices/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to Director HR', 'Refer to Director HR')], default='Pending', max_length=20)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HRUserApproval', to=settings.AUTH_USER_MODEL)),
                ('disciplinary_proceeding_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HRUserApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProbeOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_of_probe_report_date', models.DateField(blank=True, null=True)),
                ('attachment_of_probe_report', models.FileField(blank=True, upload_to='probe_reports/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to DG', 'Refer to DG')], default='Pending', max_length=20)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProbeOfficerApproval', to=settings.AUTH_USER_MODEL)),
                ('disciplinary_proceeding_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProbeOfficerApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RegularInquiryOfficerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_of_inquiry_order_date', models.DateField(blank=True, null=True)),
                ('attachment_of_inquiry_order', models.FileField(blank=True, upload_to='inquiry_order/')),
                ('alert_date_inquiry_order', models.DateField(blank=True, null=True)),
                ('alert_date_inquiry_report', models.DateField(blank=True, null=True)),
                ('issuance_of_inquiry_report_date', models.DateField(blank=True, null=True)),
                ('attachment_of_inquiry_report', models.FileField(blank=True, upload_to='inquiry_report/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Refer to Director HR', 'Refer to Director HR'), ('Refer to DG', 'Refer to DG')], default='Pending', max_length=20)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RegularInquiryOfficer', to=settings.AUTH_USER_MODEL)),
                ('disciplinary_proceeding_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RegularInquiryOfficer', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='DisciplinaryProceedingInquiry',
        ),
        migrations.AddField(
            model_name='directorhrapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DirectorHrApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='directorhrapproval',
            name='inquiry_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes'),
        ),
        migrations.AddField(
            model_name='directorhrapproval',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquirytype'),
        ),
        migrations.AddField(
            model_name='dgfirstapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFirstApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='dgfinalapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGFinalApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='dgfinalapproval',
            name='inquiry_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes'),
        ),
        migrations.AddField(
            model_name='dgfinalapproval',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquirytype'),
        ),
        migrations.AddField(
            model_name='dgapproval',
            name='disciplinary_proceeding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DGApproval', to='disciplinary_proceedings_setup.disciplinaryproceedingrequest'),
        ),
        migrations.AddField(
            model_name='dgapproval',
            name='inquiry_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquiryoutcomes'),
        ),
        migrations.AddField(
            model_name='dgapproval',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disciplinary_proceedings_setup.inquirytype'),
        ),
    ]
