# Generated by Django 4.2.3 on 2023-11-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0002_alter_job_unique_together_alter_job_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='center',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sub_wing',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tehsil',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wing',
            unique_together=set(),
        ),
    ]
