# Generated by Django 4.2.3 on 2023-11-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0003_alter_division_options_alter_center_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
