# Generated by Django 4.2.1 on 2023-11-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wing',
            options={'permissions': [('can_read_wing_name', 'Can Read Wing Name')], 'verbose_name': 'Wing_Setup', 'verbose_name_plural': 'Wings'},
        ),
    ]
