# Generated by Django 4.2.1 on 2023-11-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0007_alter_wing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region_Setup'},
        ),
    ]
