# Generated by Django 4.2.1 on 2023-11-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0008_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'permissions': [('can_view_region', 'Can View region'), ('can_add_region', 'Can Add region'), ('can_change_region', 'Can Change region'), ('can_view_d_rec_id', 'Can View d_rec_id'), ('can_add_d_rec_id', 'Can Add d_rec_id'), ('can_change_d_rec_id', 'Can Change d_rec_id'), ('can_view_division_id', 'Can View division_id'), ('can_add_division_id', 'Can Add division_id'), ('can_change_division_id', 'Can Change division_id'), ('can_view_division_name', 'Can View division_name'), ('can_add_division_name', 'Can Add division_name'), ('can_change_division_name', 'Can Change division_name')]},
        ),
    ]
