# Generated by Django 4.2.5 on 2023-12-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0009_alter_division_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wing',
            options={'permissions': [('can_read_wing_name', 'Can Read Wing Name')], 'verbose_name': 'Wing', 'verbose_name_plural': 'Wing'},
        ),
    ]
