# Generated by Django 4.2.5 on 2023-12-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0010_alter_wing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Basic Information'},
        ),
    ]
