# Generated by Django 4.2.5 on 2023-12-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0011_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionassignment',
            options={'verbose_name': 'Position'},
        ),
    ]
