# Generated by Django 5.0 on 2023-12-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0012_alter_positionassignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wing',
            options={'verbose_name': 'Wing', 'verbose_name_plural': 'Wing'},
        ),
        migrations.AddField(
            model_name='wing',
            name='director_concern_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_concern_position', to='employee_basic_information.position'),
        ),
    ]
