# Generated by Django 5.0 on 2023-12-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_basic_information', '0013_alter_wing_options_wing_director_concern_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='wing',
            name='adg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adg_position', to='employee_basic_information.position'),
        ),
    ]
