# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import termination.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Closed', 'Closed')], default='In process', max_length=30)),
                ('case_initiation_date', models.DateField(auto_now=True)),
                ('termination_effective_date', models.DateField(blank=True, null=True)),
                ('termination_category', models.CharField(choices=[('Compulsory Retirement', 'Compulsory Retirement'), ('Removal from service', 'Removal from service'), ('Dismissal from service', 'Dismissal from service')], max_length=30)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('notice_period', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=termination.models.TerminationRequest.upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
