# Generated by Django 5.0 on 2024-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetentAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('DG', 'DG'), ('CONCERN OFFICER', 'CONCERN OFFICER'), ('HR DIRECTOR', 'HR DIRECTOR'), ('HR ADMIN', 'HR ADMIN'), ('LEAVE SUPER APPROVAL', 'LEAVE SUPER APPROVAL'), ('HR User', 'HR User')], default='ADG ADMIN', max_length=30)),
            ],
        ),
    ]
