# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competent_authority', '0001_initial'),
        ('employee_basic_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competentauthority',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_basic_information.position'),
        ),
    ]
