# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competent_authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competentauthority',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
