# Generated by Django 5.0 on 2023-12-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competent_authority', '0002_initial'),
        ('employee_basic_information', '0013_alter_wing_options_wing_director_concern_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competentauthority',
            name='employee',
        ),
        migrations.AddField(
            model_name='competentauthority',
            name='designation',
            field=models.CharField(choices=[('ADG ADMIN', 'ADG ADMIN'), ('ADG TECH', 'ADG TECH'), ('DG', 'DG'), ('LEAVE SUPER APPROVAL', 'LEAVE SUPER APPROVAL')], default='ADG ADMIN', max_length=30),
        ),
        migrations.AddField(
            model_name='competentauthority',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_basic_information.position'),
        ),
    ]
