# Generated by Django 5.0 on 2023-12-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competent_authority', '0003_remove_competentauthority_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competentauthority',
            name='designation',
            field=models.CharField(choices=[('DG', 'DG'), ('LEAVE SUPER APPROVAL', 'LEAVE SUPER APPROVAL')], default='ADG ADMIN', max_length=30),
        ),
    ]
