# Generated by Django 3.2.23 on 2024-01-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competent_authority', '0005_alter_competentauthority_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competentauthority',
            name='designation',
            field=models.CharField(choices=[('DG', 'DG'), ('CONCERN OFFICER', 'CONCERN OFFICER'), ('HR DIRECTOR', 'HR DIRECTOR'), ('HR ADMIN', 'HR ADMIN'), ('LEAVE SUPER APPROVAL', 'LEAVE SUPER APPROVAL'), ('HR User', 'HR User')], default='ADG ADMIN', max_length=30),
        ),
    ]
