# Generated by Django 5.0 on 2024-05-20 05:04

import django.db.models.deletion
import resignation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Approved', 'Approved'), ('Withdraw', 'Withdraw'), ('Rejected', 'Rejected')], default='In process', max_length=20)),
                ('case_initiation_date', models.DateField(auto_now=True)),
                ('resignation_reason', models.TextField()),
                ('notice_period', models.PositiveIntegerField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=resignation.models.ResignationRequest.upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResignationApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approving_authority_designation', models.CharField(max_length=50)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('resignation_effective_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Withdraw', 'Withdraw'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('-', '-')], default='Pending', max_length=50)),
                ('approving_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('resignation_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resignation_approvals', to='resignation.resignationrequest')),
            ],
        ),
    ]
