# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resignation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Close', 'Close')], default='In process', max_length=20)),
                ('case_initiation_date', models.DateField(auto_now=True)),
                ('resignation_effective_date', models.DateField(blank=True, null=True)),
                ('resignation_reason', models.TextField()),
                ('notice_period', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=resignation.models.ResignationRequest.upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_status', 'Can View Status'), ('can_add_status', 'Can Add Status'), ('can_change_status', 'Can Change Status')],
            },
        ),
    ]
