# Generated by Django 4.2.5 on 2023-12-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resignation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resignationrequest',
            options={},
        ),
    ]
