# Generated by Django 4.2.3 on 2023-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_basic_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionDocument',
            fields=[
                ('progression_document_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('progression_document_date', models.DateField()),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Close', 'Close')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_inquiry', models.BooleanField()),
                ('major_penalities', models.BooleanField()),
                ('post_vacant', models.BooleanField()),
                ('progression_approval_date', models.DateField(blank=True, null=True)),
                ('progression_effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Marked', 'Marked'), ('Approved', 'Approved'), ('Reject', 'Reject')], max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressionDocument', to='progression.progressiondocument')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressionEmployee', to=settings.AUTH_USER_MODEL)),
                ('promote_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotejob', to='employee_basic_information.job')),
                ('promote_job_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotejobLevel', to='employee_basic_information.joblevel')),
                ('promote_ppg_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promoteppglevel', to='employee_basic_information.ppg_level_setup')),
                ('promoted_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacantPost', to='employee_basic_information.position')),
            ],
        ),
    ]
