# Generated by Django 5.0 on 2024-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_from_date', models.DateField()),
                ('holiday_to_date', models.DateField()),
                ('holiday_type', models.CharField(max_length=50)),
                ('allowed_to', models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Judaism', 'Judaism'), ('All', 'All')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday_dates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HRCelanderYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_celander_starting_date', models.DateField()),
                ('hr_celander_ending_date', models.DateField()),
                ('hr_year', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'HR Calendar Year',
            },
        ),
    ]
